method: 'grid'
name: '641final'
metric: 
    name: 'eval/product_rank'
    goal: 'minimize'   

parameters: 
  seed:
    value: 9
  model: 
    value: "llama-3.1-8b"
  batch_size: 
    value: 4
  length: 
    value: 30
  temperature:
    value: 0.1
  lr: 
    value: 0.03
  topk: 
    value: 10
  num_iter: 
    value: 1000
  test_iter: 
    value: 100
  precision: 
    value: 16
  loss_weights: 
    value: { 
      "fluency": 1, 
      "ngram": 10, 
      "target": 50 
    }
    # Modify it as a trade off between rank, fluency, n-gram

  iter_steps:
    value: [0, 50, 200, 500, 800]
  noise_stds:
    value: [0.1, 0.05, 0.01, 0.001, 0.01]  # [1, 0.5, 0.1, 0.05, 0.01]
  # result_dir: 
  #   value: "result"
  catalog: 
    value: "coffee_machines" # Choices: ["election_articles", "coffee_machines", "books", "cameras", "shampoo"] # election articles still unsovled
  random_order: 
    value: True 
  target_product_idx:
    values: [1,2,3,4,5,6,7,8,9,10]
  mode: 
    value: "self" # Choices: ["self", "transfer"]

  result_dir:
    value: "result/suffix"

  user_msg_type: 
    value: "default" # Choices: ["default", "custom"]

  comment:
    value: "training and inference with target at last and all losses applied"
